name: stocksmanager
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.0.dev <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  liquid_pull_to_refresh: ^3.0.1
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.10
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.12
  get: ^4.6.1
  image_picker: ^0.8.4+10
  flutter_staggered_grid_view: ^0.3.2
  connectivity_plus: ^2.2.1

  intl: ^0.17.0
  connectivity: ^3.0.6
  pattern_formatter: ^2.0.0
  vibration: ^1.7.3
  modal_progress_hud: ^0.1.3
  grouped_list: ^4.2.0
  group_list_view: ^1.1.1
  flutter_speed_dial: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  very_good_analysis: ^1.0.4

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

